### ISSUE TITLE
types-* packages

### ISSUE THREAD

**Issue by xhochy** [conda-forge/mypy-feedstock#42]
The newest release of `mypy` doesn't bundle the type stubs anymore but they come as separate packages called `types-*`. We should also package them here on conda-forge. Currently the package are sadly uploaded as wheels only and thus using `grayskull` is a bit annoying. There is an upstream issue requesting the upload of `sdist`s https://github.com/python/typeshed/issues/5643 and already a PR to enable that: https://github.com/typeshed-internal/stub_uploader/pull/19 We should wait for them before tackling as this should save us a lot of time.

**Comment by nehaljwani** [comment]
But ...
https://github.com/conda-forge/types_toml-feedstock
https://github.com/conda-forge/types_typed_ast-feedstock

**Comment by xhochy** [comment]
Upstream published the sdists now and I would prefer to install them as Python packages to also have the metadata available.   @nehaljwani My colleague @fhoehle would build the remaining packages. Would you also like to have your two updated to be built from an sdist? 

Also, should we add @conda-forge/mypy as a maintainer to all of them?

**Comment by nehaljwani** [comment]
👍 to all of your suggestions!
