### ISSUE TITLE
add output for "mypy and a compiler that works with mypyc"

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/mypy-feedstock#83]
### Comment:

It would be _lovely_ if there was a `mypyc` output which also dragged along an appropriate compiler, such that other packages could depend on it.

it seems like `mypyc` wouldn't be an _awful_ name for it, but maybe not _strictly_ accurate, as it _might_ theoretically work otherwise with a compiler-of-opportunity.

Motivation: https://github.com/conda-forge/staged-recipes/pull/21071

**Comment by ocefpaf** [comment]
I'm OK with that but I don't have time to implement it. Do you want to try it out?

**Comment by bollwyvl** [comment]
I'm down to try... Any suggestions on what tricks I might be able to use?
Will compiler("c") work, or is that just for building?

**Comment by ocefpaf** [comment]
> Will compiler("c") work, or is that just for building?

That is only for building but, b/c that will be a runtime dependency you can list `compilers`, I'm 80% sure that will work.

**Comment by bollwyvl** [comment]
Great! I can try it on the downstream staged-recipes PR, first, then see
about bringing it to this feedstock.

**Comment by bollwyvl** [comment]
Yeah, that worked great on https://github.com/conda-forge/staged-recipes/pull/21071. Will take a look at a PR here...
